### ISSUE TITLE
Problem in mounting the ROS car: mount: 192.168.0.100:/home/wheeltec/wheeltec_robot/mnt: can't find in /etc/fstab.

### ISSUE THREAD

**Issue by Hobart-tam** [AAE3004/Autonomous-Car-Control-Project#12]
When I want to mount the ROS car to my Ubuntu (step 6.3.1 in the User Guide), the following error occurs. How could I solve this? Thank you. 

I have successfully done the remote login by SSH (step 6.2).

![image](https://user-images.githubusercontent.com/71874558/202840989-91cc1b93-113d-4d3c-9b77-e528aaac026b.png)

**Comment by sdjkjsdh** [comment]
solution
https://www.youtube.com/watch?v=NsXJ-CfBAe0

**Comment by sdjkjsdh** [comment]
It is suggested that skip this step and begin the 'radar tracking' tutorial
