### ISSUE TITLE
Unknown Chinese character in the source code comment

### ISSUE THREAD

**Issue by Hobart-tam** [AAE3004/Autonomous-Car-Control-Project#7]
![image](https://user-images.githubusercontent.com/71874558/200164001-cf02267d-4cb5-4f05-b7b3-e9daf0468273.png)

Is the English comment the same as the unknown Chinese comment? Thank you.

Hobart Tam

**Comment by sdjkjsdh** [comment]
To recover the unknown characters into normal characters, please change the encoding format of the uVision.
Solution:
1. open keil uvision IDE
2. edit---> Configuration ----> find the 'encoding' option in Editor tab------>Change the encoding to 'Chinese GB2312(Simplified)'|

![26b295b71350c0442ffaecee8ce8ac94_0754312a67a2441e885caff35f38725f](https://user-images.githubusercontent.com/14803083/200164378-7cd4813f-1e9a-42a1-9ee4-875bf8feddcc.png)


![bc94253b0f417390f10db44bf4c617ae_3d700c3bbccb43f8ab6cd0da7ca21bb5](https://user-images.githubusercontent.com/14803083/200164412-cf5b5b63-be2a-46a0-8814-e4269e890b05.png)

**Comment by Hobart-tam** [comment]
Thank you.
